import {
  ArcType,
  Cartesian2,
  Cartesian3,
  Cartographic,
  Color,
  ColorMaterialProperty,
  Credit,
  CustomDataSource,
  CustomHeightmapTerrainProvider,
  EllipsoidGeodesic,
  Entity,
  GeoJsonDataSource,
  HeightReference,
  HorizontalOrigin,
  JulianDate,
  LabelStyle,
  Math as CesiumMath,
  NearFarScalar,
  PolylineGlowMaterialProperty,
  UrlTemplateImageryProvider,
  VerticalOrigin,
  Viewer,
  WebMercatorTilingScheme,
} from "cesium";

export const cesiumRuntime = {
  ArcType,
  Cartesian2,
  Cartesian3,
  Cartographic,
  Color,
  ColorMaterialProperty,
  Credit,
  CustomDataSource,
  CustomHeightmapTerrainProvider,
  EllipsoidGeodesic,
  Entity,
  GeoJsonDataSource,
  HeightReference,
  HorizontalOrigin,
  JulianDate,
  LabelStyle,
  Math: CesiumMath,
  NearFarScalar,
  PolylineGlowMaterialProperty,
  UrlTemplateImageryProvider,
  VerticalOrigin,
  Viewer,
  WebMercatorTilingScheme,
};
