const COUNTRY_ALIASES: Record<string, string> = {
  Aland: "Åland Islands",
  "Antigua and Barb.": "Antigua and Barbuda",
  "Bosnia and Herz.": "Bosnia and Herzegovina",
  "Br. Indian Ocean Ter.": "British Indian Ocean Territory",
  "Central African Rep.": "Central African Republic",
  "Czech Rep.": "Czech Republic",
  "Dem. Rep. Congo": "Democratic Republic of the Congo",
  "Dem. Rep. Korea": "North Korea",
  "Dominican Rep.": "Dominican Republic",
  "Eq. Guinea": "Equatorial Guinea",
  "Faeroe Is.": "Faroe Islands",
  "Falkland Is.": "Falkland Islands",
  "Fr. Polynesia": "French Polynesia",
  Korea: "South Korea",
  "N. Cyprus": "Northern Cyprus",
  "N. Mariana Is.": "Northern Mariana Islands",
  "S. Sudan": "South Sudan",
  "Solomon Is.": "Solomon Islands",
  "St. Vin. and Gren.": "Saint Vincent and the Grenadines",
  Swaziland: "Eswatini",
  "Turks and Caicos Is.": "Turks and Caicos Islands",
  "U.S. Virgin Is.": "U.S. Virgin Islands",
  "W. Sahara": "Western Sahara",
};

const COUNTRY_RELATED_TERMS: Record<string, string[]> = {
  Afghanistan: ["Afghan"],
  Albania: ["Albanian"],
  Algeria: ["Algerian"],
  Angola: ["Angolan"],
  Argentina: ["Argentine", "Argentinian"],
  Armenia: ["Armenian"],
  Australia: ["Australian"],
  Austria: ["Austrian"],
  Azerbaijan: ["Azerbaijani"],
  Bangladesh: ["Bangladeshi"],
  Belarus: ["Belarusian"],
  Belgium: ["Belgian"],
  Bolivia: ["Bolivian"],
  "Bosnia and Herzegovina": ["Bosnian"],
  Brazil: ["Brazilian"],
  Bulgaria: ["Bulgarian"],
  Cambodia: ["Cambodian"],
  Cameroon: ["Cameroonian"],
  Canada: ["Canadian"],
  Chad: ["Chadian"],
  Chile: ["Chilean"],
  China: ["Chinese"],
  Colombia: ["Colombian"],
  Croatia: ["Croatian"],
  Cuba: ["Cuban"],
  Cyprus: ["Cypriot"],
  "Czech Republic": ["Czech", "Czechia"],
  Denmark: ["Danish"],
  Ecuador: ["Ecuadorian"],
  Egypt: ["Egyptian"],
  Estonia: ["Estonian"],
  Ethiopia: ["Ethiopian"],
  Finland: ["Finnish"],
  France: ["French"],
  Georgia: ["Georgian", "Tbilisi"],
  Germany: ["German"],
  Ghana: ["Ghanaian"],
  Greece: ["Greek"],
  Haiti: ["Haitian"],
  Hungary: ["Hungarian"],
  Iceland: ["Icelandic"],
  India: ["Indian"],
  Indonesia: ["Indonesian"],
  Iran: ["Iranian"],
  Iraq: ["Iraqi"],
  Ireland: ["Irish"],
  Israel: ["Israeli"],
  Italy: ["Italian"],
  Japan: ["Japanese"],
  Jordan: ["Jordanian", "Amman"],
  Kazakhstan: ["Kazakh"],
  Kenya: ["Kenyan"],
  Kuwait: ["Kuwaiti"],
  Latvia: ["Latvian"],
  Lebanon: ["Lebanese"],
  Libya: ["Libyan"],
  Lithuania: ["Lithuanian"],
  Malaysia: ["Malaysian"],
  Mali: ["Malian"],
  Mexico: ["Mexican"],
  Moldova: ["Moldovan"],
  Mongolia: ["Mongolian"],
  Morocco: ["Moroccan"],
  Mozambique: ["Mozambican"],
  Myanmar: ["Burmese", "Burma"],
  Nepal: ["Nepali", "Nepalese"],
  Netherlands: ["Dutch"],
  "New Zealand": ["New Zealander"],
  Nicaragua: ["Nicaraguan"],
  Niger: ["Nigerien"],
  Nigeria: ["Nigerian"],
  "North Korea": ["North Korean", "Pyongyang"],
  Norway: ["Norwegian"],
  Pakistan: ["Pakistani"],
  Panama: ["Panamanian"],
  Paraguay: ["Paraguayan"],
  Peru: ["Peruvian"],
  Philippines: ["Philippine", "Filipino"],
  Poland: ["Polish"],
  Portugal: ["Portuguese"],
  Qatar: ["Qatari"],
  Romania: ["Romanian"],
  Russia: ["Russian"],
  Rwanda: ["Rwandan"],
  "Saudi Arabia": ["Saudi"],
  Senegal: ["Senegalese"],
  Serbia: ["Serbian"],
  Singapore: ["Singaporean"],
  Slovakia: ["Slovak"],
  Slovenia: ["Slovenian"],
  Somalia: ["Somali"],
  "South Africa": ["South African"],
  "South Korea": ["South Korean", "Seoul"],
  "South Sudan": ["South Sudanese"],
  Spain: ["Spanish"],
  Sudan: ["Sudanese"],
  Sweden: ["Swedish"],
  Switzerland: ["Swiss"],
  Syria: ["Syrian"],
  Taiwan: ["Taiwanese"],
  Tanzania: ["Tanzanian"],
  Thailand: ["Thai"],
  Tunisia: ["Tunisian"],
  Turkey: ["Turkish", "Türkiye"],
  Uganda: ["Ugandan"],
  Ukraine: ["Ukrainian"],
  "United Arab Emirates": ["Emirati", "UAE"],
  "United Kingdom": ["Britain", "British", "U.K."],
  "United States": ["American", "U.S.", "USA"],
  Uruguay: ["Uruguayan"],
  Venezuela: ["Venezuelan"],
  Vietnam: ["Vietnamese"],
  Yemen: ["Yemeni"],
  Zambia: ["Zambian"],
  Zimbabwe: ["Zimbabwean"],
};

export function canonicalCountryName(countryName: string) {
  return COUNTRY_ALIASES[countryName] ?? countryName;
}

export function countrySearchTerms(countryName: string) {
  const canonicalName = canonicalCountryName(countryName);
  return [
    countryName,
    canonicalName,
    ...(COUNTRY_RELATED_TERMS[canonicalName] ?? []),
  ]
    .map((term) => term.trim())
    .filter((term, index, terms) => term && terms.indexOf(term) === index);
}

function escapeRegExp(value: string) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

export function textMatchesCountry(text: string, terms: string[]) {
  return terms.some((term) =>
    new RegExp(
      `(^|[^\\p{L}\\p{N}])${escapeRegExp(term)}([^\\p{L}\\p{N}]|$)`,
      "iu",
    ).test(text),
  );
}
